In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("cleaned_text.csv")

In [3]:
df

,id,text
0,1,mixed case text lowercase
1,2,newline tab handle properly
2,3,html tag everywhere bold italic
3,4,love nlp it amazing click
4,5,number present text
...,...,...
995,996,love nlp it amazing click
996,997,repeat letter cooool loooove tweeeeet
997,998,email testexamplecom visit httpmywebsitecom
998,999,email testexamplecom visit httpmywebsitecom


## Bag of words

In [4]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()
bow = cv.fit_transform(df["text"])

In [5]:
bow[0].toarray() # we can see vector representation of each word

array([[0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 1, 0, 0, 0, 0]])

## n-grams

In [6]:
cv = CountVectorizer(ngram_range = (2,2)) #bi-gram
cv.fit_transform(df["text"]).toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 1, 0, 0],
       [0, 0, 0, ..., 1, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], shape=(1000, 65))

## Tf-Idf Vectorization

In [7]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf = TfidfVectorizer()
tfidf.fit_transform(df['text']).toarray()

array([[0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.43888044,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.43888044,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ]], shape=(1000, 73))