In [3]:
import numpy as np

In [4]:

import random

In [5]:
np.random.rand(5)


array([0.28711634, 0.73769432, 0.33441422, 0.92510283, 0.0387815 ])

In [6]:
np.random.ranf(5)

array([0.24893298, 0.27538294, 0.38280478, 0.6863011 , 0.33877941])

In [7]:
np.random.randn(5)

array([-1.96086471e+00,  2.24332558e-04, -9.04449982e-01,  5.56110404e-01,
       -9.43022008e-01])

In [8]:
np.random.randint(5)

1

In [9]:
np.random.randint(2,10,6)

array([7, 6, 9, 3, 8, 9], dtype=int32)

In [10]:
a=[1,2,3,4]
arr=np.array(a)
print(arr)
print(type(arr))
print(a)


[1 2 3 4]
<class 'numpy.ndarray'>
[1, 2, 3, 4]


In [19]:
a=[1,2,3,4]
arr=np.array(a)
print(arr)
print(arr.ndim)


[1 2 3 4]
1


In [23]:
f=[[[3,4,6,7],[6,7,8,2],[9,6,8,9]]]
arr=np.array(f)
print(arr)
print(arr.ndim)

[[[3 4 6 7]
  [6 7 8 2]
  [9 6 8 9]]]
3


In [29]:
f=[3,4,6,7]
arr=np.array(f,ndmin=5)
print(arr.ndim)
print(arr)

5
[[[[[3 4 6 7]]]]]


In [39]:
a=[[2,4,7,1],[5,7,8,1]]
arr = np.array(a)
print(arr.ndim)
print(arr.size)
print(arr.dtype)
print(arr.shape)
print(arr.min())
print(arr.max())
print(arr.argmin())
print(arr.reshape(4,2))


2
8
int64
(2, 4)
1
8
3
[[2 4]
 [7 1]
 [5 7]
 [8 1]]


In [33]:
print(arr.reshape(3,2))


ValueError: cannot reshape array of size 8 into shape (3,2)