In [1]:
import numpy as np

In [2]:
%timeit np.array([1,2,3])

1.25 μs ± 11.7 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [4]:
%time a=[1,2,3,4]

CPU times: total: 0 ns
Wall time: 0 ns


In [6]:
f=[5,6,7,8]
 print(f) #print list
k=np.array(f)
print(k) #print array

[5, 6, 7, 8]
[5 6 7 8]


In [8]:
print(type(f))
print(type(k))

<class 'list'>
<class 'numpy.ndarray'>


In [10]:
np.zeros(7)

array([0., 0., 0., 0., 0., 0., 0.])

In [13]:
np.ones(4)

array([1., 1., 1., 1.])

In [18]:
np.arange(1,20,3)  #1 say lay kal 20 tak num 3 k gap sy

array([ 1,  4,  7, 10, 13, 16, 19])

In [25]:
np.linspace(0,10,5) #divide into 5 equal parts

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [30]:
np.empty(4)

array([6.95324998e-310, 1.45494993e-311, 1.45492762e-311, 4.94065646e-324])

In [31]:
np.random.rand(3) #0 sy 1 k beech

array([0.68841907, 0.07916805, 0.76723117])

In [34]:
np.random.seed()
np.random.rand(3) #0 sy 1 k beech


array([0.98690509, 0.2106335 , 0.7389495 ])

In [35]:
np.random.seed()
num=np.random.rand(3) #0 sy 1 k beech
print(num)

[0.33549253 0.85763537 0.74112552]


In [36]:
 np.random.randn(5)  # generate a random value close to zero randn  ka matlab ha 0 k pass

array([ 0.91902967,  0.18119801,  0.31886968, -0.87188673, -0.22415476])

In [37]:
np.random.ranf(5) #0 sy 1 but also in floating

array([0.24623077, 0.71489235, 0.3272468 , 0.40328101, 0.95116172])

In [38]:
np.random.randint(5,12,5)

array([ 6, 10,  9,  5, 11], dtype=int32)

# *Dimension*


In [72]:
j=np.array([3,6,8])
print(j.ndim)
j
j=np.array([[3,6,8],[1,2,3]])
print(j.ndim)

1
2


In [45]:
j=np.array([[[3,6,8],[1,2,7]]])
print(j.ndim)  #2x3
j

3


array([[[3, 6, 8],
        [1, 2, 7]]])

In [46]:
j=np.array([[3,6],[1,2],[9,8]])
print(j.ndim)     #3x2
j

2


array([[3, 6],
       [1, 2],
       [9, 8]])

In [55]:
#khud sy dimension bnanay k liy
s = [1,2,3,4]   #first list li ha then
arr = np.array(s,ndmin=3)
print(arr.ndim)
arr

3


array([[[1, 2, 3, 4]]])

In [50]:
t = [1,2,3,4]
arr = np.array(t,ndmin=3)
print(arr.ndim)
arr

3


array([[[1, 2, 3, 4]]])

# *Array Attributes and Methods*


In [58]:
a = np.array([[2,4,9,4],[5,2,1,8]])
a
a.shape    #row x column batati ha

(2, 4)

In [59]:
a.dtype   #datatype

dtype('int64')

In [60]:
  a.size    #totall element

8

In [61]:
a.ndim

2

In [64]:
a.max()

np.int64(9)

In [65]:
a.min()

np.int64(1)

In [66]:
a.argmax()   #tell maximum value location by indexing

np.int64(2)

In [69]:
print(a)
a.argmin()    #location of min num

[[2 4 9 4]
 [5 2 1 8]]


np.int64(6)

In [70]:
a.reshape(4,2)   #convert row x column into column x row as 2 x 4 into 4 x 2

array([[2, 4],
       [9, 4],
       [5, 2],
       [1, 8]])

# *Operation on Array*

In [76]:
e= np.array([22,55,77])
r=e.copy()
r

array([22, 55, 77])

In [77]:
#Append (add at the last)
np.append(e,88)

array([22, 55, 77, 88])

# *insert*

In [84]:
print(e)
np.insert(e,1,33) #index 1 per value add 

[22 55 77]


array([22, 33, 55, 77])

In [85]:
q = np.array([82,3,11,46])
np.sort(q)

array([ 3, 11, 46, 82])

In [89]:
print(q)
np.delete(q,0)  #index per remove krta ha

[82  3 11 46]


array([ 3, 11, 46])

# *concatenate*

In [91]:
print(s)
print(q)

[1, 2, 3, 4]
[82  3 11 46]


In [92]:
np.concatenate((s,q))

array([ 1,  2,  3,  4, 82,  3, 11, 46])

In [94]:
arr =np.array([1,2,3,4])
np.split(arr ,2)

[array([1, 2]), array([3, 4])]

# *Practice Questions* 

Python list se NumPy array banao

In [95]:
a=[1,2,3,4]
print(a)
arr=np.array(a)
print(arr)

[1, 2, 3, 4]
[1 2 3 4]


arange() se 1–20 tak array banao

In [96]:
np.arange(1,20,1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

reshape() use karke 2×3 matrix banao

In [109]:
b=np.array([[9,8],[5,4],[1,0]])
b.shape

(3, 2)

In [110]:
b.reshape(2,3)

array([[9, 8, 5],
       [4, 1, 0]])

In [111]:
b.max()

np.int64(9)

In [112]:
b.min()

np.int64(0)

In [114]:
b.argmax()

np.int64(0)

In [115]:
b.argmin()

np.int64(5)