In [1]:
import numpy as np

# *Data Loading and saving*

In [3]:
a=[1,2,3,4]
arr=np.array(a)
print(arr)

[1 2 3 4]


In [4]:
np.save("numpydat2.npy",arr)

In [6]:
arr=np.load("numpydat2.npy")

In [7]:
print(arr)

[1 2 3 4]


# *Multiple array save and load.npz*

In [8]:
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])
np.savez("MultipleArray.npz",a=a,b=b)


In [9]:
c=np.load("MultipleArray.npz")
print(c["a"])
print(c["b"])

[1 2 3 4]
[5 6 7 8]


# *Indexing*

In [10]:
d=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(d.ndim)
d

2


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
print(d[1,2])   #single element access krna by indexing Row x column

6


In [17]:
(d[1])   #Compelete Row

array([4, 5, 6])

In [16]:
(d[ : 1])   #Compelete Column

array([[1, 2, 3]])

In [19]:
d[:]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [20]:
d[1:3,1:3]

array([[5, 6],
       [8, 9]])

In [21]:
d[0:2
    ]

array([[1, 2, 3],
       [4, 5, 6]])

In [22]:
f= np.array([10,15,20,25,30])
f>20

array([False, False, False,  True,  True])

In [23]:
f[f>20]   #print number Greater then 20

array([25, 30])

In [26]:
(f [f % 2 ==0])   #print number divided by 2

array([10, 20, 30])

In [27]:
f

array([10, 15, 20, 25, 30])

In [28]:
f +5

array([15, 20, 25, 30, 35])

In [29]:
f-3

array([ 7, 12, 17, 22, 27])

In [32]:
f + np.array([4,4,4,4,4])

array([14, 19, 24, 29, 34])

In [33]:
k = np.array([[10,20],[30,40],[50,60]])
k *np.array([2,2])

array([[ 20,  40],
       [ 60,  80],
       [100, 120]])

In [35]:
t=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [36]:
t[1]

array([4, 5, 6])

In [37]:
t>5

array([[False, False, False],
       [False, False,  True],
       [ True,  True,  True]])

In [38]:
t +10

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [39]:
np.save("pracQ.npy",t)

In [41]:
t =np.load("pracQ.npy")