In [1]:
import numpy as np

In [3]:
a=[1,2,3]
arr=np.array(a)
print(arr)
b=np.copy(a)
print(b)


[1 2 3]
[1 2 3]


In [5]:
a=[1,2]
b=[3,4]
np.array(a)
np.array(b)
np.concatenate((a,b))

array([1, 2, 3, 4])

In [10]:
k=[2,7,8,2,4]
arr=np.array(k)
print(arr)

[2 7 8 2 4]


In [12]:
a=np.arange(1,21,1)
print(a)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [13]:
c=[[3,6,8],[1,2,9]]
k=np.array(c)
print(k)
print(k.ndim)

[[3 6 8]
 [1 2 9]]
2


In [14]:
k.reshape(3,2)

array([[3, 6],
       [8, 1],
       [2, 9]])

In [15]:
k.max()

np.int64(9)

In [16]:
k.argmax()

np.int64(5)

# *Saving And Loading of Numpy Array*

In [25]:
arr=np.array([1,2,3,4])

np.save('data.npy',arr)


In [27]:
arr=np.load('data.npy')
print(arr)

[1 2 3 4]


In [28]:
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])
np.savez("Multiple.npz",a=a,b=b)


In [29]:
data=np.load("Multiple.npz")
print(data["a"])
print(data["b"])


[1 2 3 4]
[5 6 7 8]


# *Indexing*

In [6]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
print(arr[1,2])

6


In [8]:
print(arr[:])

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [10]:
print(arr[1])

[4 5 6]


In [12]:
print(arr[:,2])

[3 6 9]


In [15]:
print(arr[0:2,0:2])

[[1 2]
 [4 5]]


In [17]:
print(arr[1,1])

5


In [18]:
import numpy as np
arr=np.array([[11,22,33],[4,5,6],[7,8,9]])
arr

array([[11, 22, 33],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [19]:
print(arr[1])

[4 5 6]


In [20]:
arr[arr>5]

array([11, 22, 33,  6,  7,  8,  9])

In [21]:
arr+10

array([[21, 32, 43],
       [14, 15, 16],
       [17, 18, 19]])

In [22]:
import numpy as np
np.save("khadi.npy",arr)

In [23]:
arr=np.load("khadi.npy")

In [24]:
print(arr)

[[11 22 33]
 [ 4  5  6]
 [ 7  8  9]]
